# OpenAI API configuration

api_key = "sk-spfw3nYrr2wie9yUkBnnvrP6MWqxT0Q7wqiTrWJVGtor3ctN"
api_type = "openai"  # Change to "azure" if using Azure

# If you are using the API service provided by Microsoft Azure, uncomment and fill in the following lines:
#[azure]
#api_base = "your_azure_api_base_url"
#api_version = "your_azure_api_version"

# You.com search API configuration
[youcom]
api_key = "your_youcom_api_key"