# Set up OpenAI API key.
OPENAI_API_KEY="sk-spfw3nYrr2wie9yUkBnnvrP6MWqxT0Q7wqiTrWJVGtor3ctN"
# If you are using the API service provided by OpenAI, include the following line:
OPENAI_API_TYPE="openai"
# If you are using the API service provided by Microsoft Azure, include the following lines:
OPENAI_API_TYPE="azure"
AZURE_API_BASE="your_azure_api_base_url"
AZURE_API_VERSION="your_azure_api_version"
# Set up You.com search API key.
YDC_API_KEY="your_youcom_api_key"